NumPy Retail Analytics Assignment
Business Scenario
You are working as a Data Analyst for SmartMart Retail Stores. The company operates five stores in different cities and sells six major product categories.

Management wants to analyze sales performance, expenses, profits, targets, discounts, inventory, and store-level performance using NumPy.

You are provided with two main NumPy arrays:

sales_data — monthly sales revenue generated by each store for different product categories.
cost_data — total cost incurred by each store for the same product categories.

Part 1: Dataset Creation

In [4]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


Part 2: Basic Array Understanding
Question 1: Array Dimensions
The finance manager wants to confirm how many stores and product categories are present in the data.

Write NumPy code to display:

Number of dimensions in sales_data
Shape of sales_data
Total number of values
Data type of the array
Memory occupied by the array

In [5]:
import numpy as np
print("Number of dimensions:", sales_data.ndim)
print("Shape of sales_data:", sales_data.shape)
print("Total number of values:", sales_data.size)
print("Data type:", sales_data.dtype)
print("Memory occupied (bytes):", sales_data.nbytes)

Number of dimensions: 2
Shape of sales_data: (5, 6)
Total number of values: 30
Data type: int64
Memory occupied (bytes): 240


Question 2: Store and Category Count
Calculate the following:

Total number of stores
Total number of product categories
Total number of store-category combinations

In [6]:
# 1. Total number of stores
total_stores = len(stores)
# Alternatively using shape: total_stores = sales_data.shape[0]
print("Total number of stores:", total_stores)
# 2. Total number of product categories
total_categories = len(categories)
# Alternatively using shape: total_categories = sales_data.shape[1]
print("Total number of product categories:", total_categories)
# 3. Total number of store-category combinations
total_combinations = sales_data.size
# Alternatively: total_combinations = total_stores * total_categories
print("Total number of store-category combinations:", total_combinations)

Total number of stores: 5
Total number of product categories: 6
Total number of store-category combinations: 30


Question 3: Sales Data Type Conversion
The reporting application requires sales values in floating-point format.

Convert sales_data into:

float32
float64
Compare the memory used by both arrays.

In [7]:
# 1. Convert sales_data to float32
sales_float32 = sales_data.astype(np.float32)
# 2. Convert sales_data to float64
sales_float64 = sales_data.astype(np.float64)
# 3. Compare the memory used by both arrays
print("Memory used by float32 array:", sales_float32.nbytes, "bytes")
print("Memory used by float64 array:", sales_float64.nbytes, "bytes")
# Comparison statement
print(f"The float64 array uses {sales_float64.nbytes / sales_float32.nbytes:.0f}x as much memory as the float32 array.")

Memory used by float32 array: 120 bytes
Memory used by float64 array: 240 bytes
The float64 array uses 2x as much memory as the float32 array.


Part 3: Indexing and Data Extraction
Question 4: Bengaluru Store Analysis
The Bengaluru regional manager wants to review sales for all product categories.

Extract and display the complete sales row for Bengaluru.

In [8]:
bengaluru_sales = sales_data[0]
print("Bengaluru Sales:", bengaluru_sales)

Bengaluru Sales: [850000 420000 310000 275000 190000 225000]


Question 5: Mumbai Cost Analysis
Extract the total cost incurred by the Mumbai store for all product categories.

In [9]:
print("mumbai cost:", cost_data[3])

mumbai cost: [790000 390000 265000 250000 165000 205000]


Question 6: Electronics Sales Across Stores
The electronics department wants to compare its sales performance across all five stores.

Extract the Electronics sales column from sales_data.

In [10]:
print("electronics sales:",sales_data[:,0])

electronics sales: [ 850000  780000  920000 1050000  690000]


Question 7: Clothing Cost Across Stores
Extract the Clothing cost for every store from cost_data.

In [11]:
print("clothing cost:",cost_data[:,3])

clothing cost: [205000 225000 195000 250000 170000]


Question 8: Hyderabad Furniture Performance
Find the following for Hyderabad:

Furniture sales
Furniture cost
Furniture profit

In [12]:
print("furniture sales:",sales_data[1,3])
print("furniture cos:",cost_data[1,3])
print(" furniture profit:",sales_data[1,3]-cost_data[1,3])

furniture sales: 310000
furniture cos: 225000
 furniture profit: 85000



Question 9: Chennai Category Range
Extract Chennai’s sales for the following categories:

Groceries
Clothing
Furniture
Use array slicing.

In [13]:
chennai_range_sales = sales_data[2, 1:4]
print("Chennai Sales (Groceries, Clothing, Furniture):", chennai_range_sales)


Chennai Sales (Groceries, Clothing, Furniture): [390000 340000 260000]


Question 10: Selected Store Analysis
Extract sales data for:

Bengaluru
Chennai
Pune
Include only:

Electronics
Clothing
Beauty
Use advanced indexing.

In [14]:
selected_sales = sales_data[[0, 2, 4]][:, [0, 2, 4]]
print("Selected Sales Data:\n", selected_sales)

Selected Sales Data:
 [[850000 310000 190000]
 [920000 340000 185000]
 [690000 280000 175000]]


Part 4: Sales Aggregation
Question 11: Company-Wide Sales
Calculate the total sales revenue generated by all stores and all categories.

In [15]:
total_sales = np.sum(sales_data)
print("total sales revenue:",total_sales)

total sales revenue: 11675000


Question 12: Store-Wise Sales
Calculate total sales revenue for each store.

Display the result together with the store names.

Expected output format:

Bengaluru: total sales
Hyderabad: total sales
Chennai: total sales
Mumbai: total sales
Pune: total sales

In [16]:

for i in range(len(stores)):
    store_sales = np.sum(sales_data[i])
    print(f"{stores[i]}:{store_sales}")


Bengaluru:2270000
Hyderabad:2295000
Chennai:2310000
Mumbai:2820000
Pune:1980000


Question 13: Category-Wise Sales
Calculate total sales for each product category across all stores.

Display each category name with its total sales.

In [17]:
total_sales_per_category = np.sum(sales_data, axis=0)
for i in range(len(categories)):
  print(f"{categories[i]}:{total_sales_per_category[i]}")

Electronics:4290000
Groceries:2185000
Clothing:1600000
Furniture:1415000
Beauty:1010000
Sports:1175000


Question 14: Average Sales Per Store
Calculate the average sales generated by each store across all six product categories.

In [18]:
# Calculate average sales per store across the 6 product categories
avg_sales_per_store = np.mean(sales_data, axis=1)

for store, avg in zip(stores, avg_sales_per_store):
    print(f"{store}: ₹{avg:,.2f}")

Bengaluru: ₹378,333.33
Hyderabad: ₹382,500.00
Chennai: ₹385,000.00
Mumbai: ₹470,000.00
Pune: ₹330,000.00


Question 15: Average Sales Per Category
Calculate the average sales of each product category across the five stores.



In [19]:
avg_sales_per_category = np.mean(sales_data, axis=0)

for category, avg in zip(categories, avg_sales_per_category):
    print(f"{category}: {avg:,.2f}")

Electronics: 858,000.00
Groceries: 437,000.00
Clothing: 320,000.00
Furniture: 283,000.00
Beauty: 202,000.00
Sports: 235,000.00


Question 16: Highest-Selling Store
Identify:

Index of the store with the highest total sales
Name of the store
Total sales generated by that store
Use np.argmax().

In [20]:
total_sales_per_store = np.argmax(np.sum(sales_data, axis=1))
print("index of the store with the highest total sales:", total_sales_per_store)
print("name of the store:",stores[total_sales_per_store])
print("total sales generated by that store:",np.sum(sales_data[total_sales_per_store]))


index of the store with the highest total sales: 3
name of the store: Mumbai
total sales generated by that store: 2820000


Question 17: Lowest-Selling Store
Identify the store with the lowest overall sales.

Use np.argmin()

In [21]:
print("index of the store with the lowest total sales:", total_sales_per_store)
print("name of the store:",stores[total_sales_per_store])
print("total sales generated by that store:",np.sum(sales_data[total_sales_per_store]))

index of the store with the lowest total sales: 3
name of the store: Mumbai
total sales generated by that store: 2820000


Question 18: Highest-Selling Category
Find the product category that generated the highest total sales across the company.

In [22]:
highest_cat_idx = np.argmax(np.sum(sales_data, axis=0))
print("Index of highest-selling category:", highest_cat_idx)
print("Name of category:", categories[highest_cat_idx])
print("Total sales generated:", np.sum(sales_data[:, highest_cat_idx]))

Index of highest-selling category: 0
Name of category: Electronics
Total sales generated: 4290000


Question 19: Lowest-Selling Category
Find the product category with the lowest total sales across all stores.

In [23]:
lowest_cat_idx = np.argmax(np.sum(sales_data, axis=0))
print("Index of lowest-selling category:", lowest_cat_idx)
print("Name of category:", categories[lowest_cat_idx])
print("Total sales generated:", np.sum(sales_data[:, lowest_cat_idx]))


Index of lowest-selling category: 0
Name of category: Electronics
Total sales generated: 4290000


Part 5: Cost Analysis
Question 20: Total Company Cost
Calculate the total cost incurred by SmartMart across all stores and product categories.



In [24]:
total_cost = np.sum(cost_data)
print("Total cost incurred by SmartMart:", total_cost)


Total cost incurred by SmartMart: 8600000


Question 21: Store-Wise Cost
Calculate the total cost incurred by each store.

In [25]:
# Calculate total cost per store
store_costs = np.sum(cost_data, axis=1)
for i in range(len(stores)):
    print(f"{stores[i]}: {store_costs[i]}")

Bengaluru: 1665000
Hyderabad: 1685000
Chennai: 1710000
Mumbai: 2065000
Pune: 1475000


Question 22: Category-Wise Cost
Calculate the total cost incurred for each product category across all stores.

In [26]:
# Calculate total cost per category across all stores
cat_costs = np.sum(cost_data, axis=0)
for i in range(len(categories)):
    print(f"{categories[i]}: {cat_costs[i]}")


Electronics: 3250000
Groceries: 1660000
Clothing: 1145000
Furniture: 1045000
Beauty: 665000
Sports: 835000



Question 23: Most Expensive Store
Identify the store with the highest total operating cost.

In [27]:
# Find index of store with highest total cost
max_cost_idx = np.argmax(np.sum(cost_data, axis=1))
print("Index of most expensive store:", max_cost_idx)
print("Name of store:", stores[max_cost_idx])
print("Total cost incurred:", np.sum(cost_data[max_cost_idx]))

Index of most expensive store: 3
Name of store: Mumbai
Total cost incurred: 2065000


Question 24: Lowest-Cost Store
Identify the store with the lowest total cost.

In [28]:
# Find index of store with lowest total cost
min_cost_idx = np.argmin(np.sum(cost_data, axis=1))
print("Index of lowest-cost store:", min_cost_idx)
print("Name of store:", stores[min_cost_idx])
print("Total cost:", np.sum(cost_data[min_cost_idx]))

Index of lowest-cost store: 4
Name of store: Pune
Total cost: 1475000


Question 25: Most Expensive Product Category
Determine which product category has the highest total cost across all stores.

In [29]:
max_cost_cat_idx = np.argmax(np.sum(cost_data, axis=0))

print("Index of most expensive category:", max_cost_cat_idx)
print("Name of category:", categories[max_cost_cat_idx])
print("Total cost incurred:", np.sum(cost_data[:, max_cost_cat_idx]))

Index of most expensive category: 0
Name of category: Electronics
Total cost incurred: 3250000


Part 6: Profit Analysis Using Two Arrays
Question 26: Profit Matrix
Calculate the profit generated for every store and product category.

Use:

profit_data = sales_data - cost_data
Display the complete profit matrix.

In [30]:
profit_data = sales_data - cost_data
print("Profit Matrix:")
print(profit_data)

Profit Matrix:
[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


Question 27: Store-Wise Profit
Calculate the total profit generated by each store.

In [31]:
# Calculate total profit for each store across rows
store_profits = np.sum(profit_data, axis=1)
for i in range(len(stores)):
    print(f"{stores[i]}: {store_profits[i]}")

Bengaluru: 605000
Hyderabad: 610000
Chennai: 600000
Mumbai: 755000
Pune: 505000


Question 28: Category-Wise Profit
Calculate the total profit generated by each product category.

In [32]:
# Calculate total profit for each category across columns (axis=0)
cat_profits = np.sum(profit_data, axis=0)
for i in range(len(categories)):
    print(f"{categories[i]}: {cat_profits[i]}")

Electronics: 1040000
Groceries: 525000
Clothing: 455000
Furniture: 370000
Beauty: 345000
Sports: 340000


Question 29: Most Profitable Store
Identify the store that generated the highest total profit.

Display:

Store name
Total sales
Total cost
Total profit

In [33]:
# Find index of store with highest total profit
max_profit_idx = np.argmax(np.sum(profit_data, axis=1))
print("Store name:", stores[max_profit_idx])
print("Total sales:", np.sum(sales_data[max_profit_idx]))
print("Total cost:", np.sum(cost_data[max_profit_idx]))
print("Total profit:", np.sum(profit_data[max_profit_idx]))

Store name: Mumbai
Total sales: 2820000
Total cost: 2065000
Total profit: 755000


Question 30: Least Profitable Store
Identify the store that generated the lowest total profit.

In [34]:
# Find index of store with lowest total profit
min_profit_idx = np.argmin(np.sum(profit_data, axis=1))
print("Store name:", stores[min_profit_idx])
print("Total sales:", np.sum(sales_data[min_profit_idx]))
print("Total cost:", np.sum(cost_data[min_profit_idx]))
print("Total profit:", np.sum(profit_data[min_profit_idx]))

Store name: Pune
Total sales: 1980000
Total cost: 1475000
Total profit: 505000


Question 31: Most Profitable Category
Find the category with the highest total profit across all stores.

In [35]:
# Find index of category with highest total profit
max_profit_cat_idx = np.argmax(np.sum(profit_data, axis=0))
print("Index of most profitable category:", max_profit_cat_idx)
print("Name of category:", categories[max_profit_cat_idx])
print("Total profit generated:", np.sum(profit_data[:, max_profit_cat_idx]))

Index of most profitable category: 0
Name of category: Electronics
Total profit generated: 1040000


Question 32: Least Profitable Category
Find the category with the lowest total profit.

In [36]:
# Find index of category with lowest total profit
min_profit_cat_idx = np.argmin(np.sum(profit_data, axis=0))
print("Index of least profitable category:", min_profit_cat_idx)
print("Name of category:", categories[min_profit_cat_idx])
print("Total profit generated:", np.sum(profit_data[:, min_profit_cat_idx]))

Index of least profitable category: 5
Name of category: Sports
Total profit generated: 340000


Question 33: Maximum Individual Profit
Find the highest profit generated by any single store-category combination.

Display:

Profit amount
Store name
Product category
Use np.unravel_index().

In [37]:
max_profit_cat_idx = np.argmax(profit_data)
max_profit_store_idx, max_profit_cat_idx = np.unravel_index(max_profit_cat_idx, profit_data.shape)
print("maximum profit:", profit_data[max_profit_store_idx, max_profit_cat_idx])
print("store name:", stores[max_profit_store_idx])
print("product category: ", categories[max_profit_cat_idx ])

maximum profit: 260000
store name: Mumbai
product category:  Electronics


Question 34: Minimum Individual Profit
Find the smallest profit generated by a store-category combination.

Display the corresponding store and category.

In [38]:
# Find 2D index of the minimum profit using np.unravel_index
min_idx = np.unravel_index(np.argmin(profit_data), profit_data.shape)
min_profit_amount = profit_data[min_idx]
min_profit_store = stores[min_idx[0]]
min_profit_category = categories[min_idx[1]]
print("Minimum profit:", min_profit_amount)
print("Store name:", min_profit_store)
print("Product category:", min_profit_category)

Minimum profit: 55000
Store name: Pune
Product category: Furniture



Part 7: Profit Margin Analysis
Question 35: Profit Margin Matrix
Calculate the profit margin percentage for every store-category combination.

Use:

profit_margin = (profit_data / sales_data) * 100
Round the result to two decimal places.

In [39]:
# Calculate profit margin percentage
profit_margin = np.round((profit_data / sales_data) * 100, 2)
print("Profit Margin Matrix (%):")
print(profit_margin)

Profit Margin Matrix (%):
[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


Question 36: Store-Wise Profit Margin
Calculate the overall profit margin percentage for each store using:

Store Profit Margin =
Total Store Profit / Total Store Sales × 100

In [40]:
# Calculate store-wise profit margins
store_profits = np.sum(profit_data, axis=1)
store_sales = np.sum(sales_data, axis=1)
store_margins = np.round((store_profits / store_sales) * 100, 2)
for i in range(len(stores)):
    print(f"{stores[i]}: {store_margins[i]}%")

Bengaluru: 26.65%
Hyderabad: 26.58%
Chennai: 25.97%
Mumbai: 26.77%
Pune: 25.51%


Question 37: Category-Wise Profit Margin
Calculate the overall profit margin percentage for each product category.

In [41]:
# Calculate category-wise profit margins
cat_profits = np.sum(profit_data, axis=0)
cat_sales = np.sum(sales_data, axis=0)
cat_margins = np.round((cat_profits / cat_sales) * 100, 2)

for i in range(len(categories)):
    print(f"{categories[i]}: {cat_margins[i]}%")

Electronics: 24.24%
Groceries: 24.03%
Clothing: 28.44%
Furniture: 26.15%
Beauty: 34.16%
Sports: 28.94%


Question 38: Best Store by Profit Margin
Identify the store with the highest overall profit margin.



In [42]:
# Find index of the store with the highest overall profit margin
max_margin_idx = np.argmax(store_margins)
print("Store name:", stores[max_margin_idx])
print("Profit margin:", f"{store_margins[max_margin_idx]}%")

Store name: Mumbai
Profit margin: 26.77%


Question 39: Best Category by Profit Margin
Identify the product category with the highest profit margin.

In [43]:
# 1. Calculate category profit margins
cat_profits = np.sum(profit_data, axis=0)
cat_sales = np.sum(sales_data, axis=0)
cat_margins = np.round((cat_profits / cat_sales) * 100, 2)

# 2. Find category with the highest profit margin
max_cat_margin_idx = np.argmax(cat_margins)

print("Category name:", categories[max_cat_margin_idx])
print("Profit margin:", f"{cat_margins[max_cat_margin_idx]}%")

Category name: Beauty
Profit margin: 34.16%


Question 40: Low-Margin Transactions
Management considers a profit margin below 22% to be weak.

Find all store-category combinations where the profit margin is below 22%.

Display:

Store
Category
Sales
Cost
Profit
Profit margin
Use Boolean indexing.

In [44]:
# Create boolean mask for profit margin below 22%
low_margin_mask = profit_margin < 22

# Get indices where the condition is True
low_margin_indices = np.argwhere(low_margin_mask)

for store_idx, cat_idx in low_margin_indices:
    print("Store:", stores[store_idx])
    print("Category:", categories[cat_idx])
    print("Sales:", sales_data[store_idx, cat_idx])
    print("Cost:", cost_data[store_idx, cat_idx])
    print("Profit:", profit_data[store_idx, cat_idx])
    print("Profit margin:", f"{profit_margin[store_idx, cat_idx]}%\n")

Part 8: Boolean Filtering
Question 41: High Sales Values
Find all sales values greater than ₹5,00,000.

In [45]:
# Extract all sales values greater than 500,000
high_sales = sales_data[sales_data > 500000]
print("Sales values greater than 5,00,000:")
print(high_sales)

Sales values greater than 5,00,000:
[ 850000  780000  920000 1050000  510000  690000]


Question 42: Low Sales Values
Find all sales values below ₹2,00,000.



In [46]:
# Extract all sales values less than 200,000
low_sales = sales_data[sales_data < 200000]

print("Sales values less than ₹2,00,000:")
print(low_sales)

Sales values less than ₹2,00,000:
[190000 185000 175000]


Question 43: High Profit Values
Find all store-category combinations where profit is greater than ₹1,50,000.

In [47]:
high_profit_mask = profit_data > 150000
high_profit_indices = np.argwhere(high_profit_mask)
for store_idx, cat_idx in high_profit_indices:
    print(f"Store: {stores[store_idx]}, Category: {categories[cat_idx]}, Profit: ₹{profit_data[store_idx, cat_idx]:,}")

Store: Bengaluru, Category: Electronics, Profit: ₹210,000
Store: Hyderabad, Category: Electronics, Profit: ₹190,000
Store: Chennai, Category: Electronics, Profit: ₹220,000
Store: Mumbai, Category: Electronics, Profit: ₹260,000
Store: Pune, Category: Electronics, Profit: ₹160,000


Question 44: Moderate Sales Range
Find sales values between ₹2,50,000 and ₹5,00,000.

Use np.logical_and().

In [48]:
moderate_sales_mask = np.logical_and(sales_data >= 250000, sales_data <= 500000)
moderate_sales = sales_data[moderate_sales_mask]
print("Sales values between 2,50,000 and 5,00,000:")
print(moderate_sales)

Sales values between 2,50,000 and 5,00,000:
[420000 310000 275000 460000 295000 310000 390000 340000 260000 375000
 345000 250000 290000 405000 280000]


Question 45: Premium Performance
A store-category combination is considered premium when:

Sales are greater than ₹5,00,000
Profit is greater than ₹1,50,000
Find all premium-performing combinations.

In [49]:
premium_mask = (sales_data > 500000) & (profit_data > 150000)
premium_indices = np.argwhere(premium_mask)

for store_idx, cat_idx in premium_indices:
    print(f"Store: {stores[store_idx]}")
    print(f"Category: {categories[cat_idx]}")
    print(f"Sales: {sales_data[store_idx, cat_idx]}")
    print(f"Profit: {profit_data[store_idx, cat_idx]:}")

Store: Bengaluru
Category: Electronics
Sales: 850000
Profit: 210000
Store: Hyderabad
Category: Electronics
Sales: 780000
Profit: 190000
Store: Chennai
Category: Electronics
Sales: 920000
Profit: 220000
Store: Mumbai
Category: Electronics
Sales: 1050000
Profit: 260000
Store: Pune
Category: Electronics
Sales: 690000
Profit: 160000


Question 46: Underperforming Combinations
A store-category combination is considered underperforming when:

Sales are below ₹2,50,000
Profit margin is below 25%
Find all such combinations.

In [50]:

underperforming_mask = (sales_data < 250000) & (profit_margin < 25)
underperforming_indices = np.argwhere(underperforming_mask)
print("Underperforming Combinations:")
for store_idx, cat_idx in underperforming_indices:
    print(f"Store: {stores[store_idx]}")
    print(f"Category: {categories[cat_idx]}")
    print(f"Sales: ₹{sales_data[store_idx, cat_idx]:,}")
    print(f"Profit Margin: {profit_margin[store_idx, cat_idx]}%")

Underperforming Combinations:
Store: Pune
Category: Furniture
Sales: ₹225,000
Profit Margin: 24.44%


Question 47: Category Performance Classification
Create a new array that classifies every sales value as:

"High" when sales are at least ₹5,00,000
"Medium" when sales are between ₹2,50,000 and ₹4,99,999
"Low" when sales are below ₹2,50,000
Use np.where() or np.select().

In [51]:
# Classify sales values using np.select
conditions = [sales_data >= 500000, sales_data >= 250000]
choices = ["High", "Medium"]
sales_classification = np.select(conditions, choices, default="Low")
print(sales_classification)

[['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'High' 'Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'Medium' 'Medium' 'Low' 'Low' 'Low']]


Part 9: Target-Based Analysis
Use the following category-wise monthly sales targets:

sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])

Question 48: Target Comparison
Compare every store’s category sales against sales_targets.

Use NumPy broadcasting.

In [52]:
# Define category-wise sales targets
sales_targets = np.array([800000, 450000, 320000, 300000, 200000, 230000])

# Compare using broadcasting
target_comparison = sales_data >= sales_targets

print("Target Achieved Matrix (True = Met/Exceeded, False = Below Target):")
print(target_comparison)

Target Achieved Matrix (True = Met/Exceeded, False = Below Target):
[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


Question 49: Target Achievement Matrix
Create a Boolean array where:

True means the store achieved the category target
False means the store failed to achieve the target

In [53]:
# Boolean array for target achievement using broadcasting
target_achieved = sales_data >= sales_targets
print("Target Achievement Matrix:")
print(target_achieved)

Target Achievement Matrix:
[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


Question 50: Target Achievement Count
Calculate the number of categories in which each store achieved its target.

In [54]:
# Calculate the number of targets achieved per store (sum along rows)
targets_achieved_per_store = np.sum(target_achieved, axis=1)
for store, count in zip(stores, targets_achieved_per_store):
    print(f"{store}: {count}")

Bengaluru: 1
Hyderabad: 4
Chennai: 2
Mumbai: 6
Pune: 0


Question 51: Best Target-Performing Store
Find the store that achieved the highest number of category targets.

In [55]:
highest_category = np.argmax(targets_achieved_per_store)
print("store with highest number of category:", stores[highest_category])

store with highest number of category: Mumbai


Question 52: Target Achievement by Category
Calculate how many stores achieved the target for each product category.

In [56]:
store_achieved_per_category = np.sum(target_achieved, axis=0)
for category, count in zip (categories, store_achieved_per_category):
  print(f"{category}: {count} ")


Electronics: 3 
Groceries: 2 
Clothing: 2 
Furniture: 2 
Beauty: 2 
Sports: 2 


Question 53: Sales Target Variance
Calculate the difference between actual sales and target sales for every store.

Use:

Variance = Actual Sales - Target Sales

In [57]:
target_sales = np.array([800000, 450000, 320000, 300000, 200000, 230000])
actual_sales = np.sum(sales_data, axis=0)
variance = actual_sales - target_sales
for store, var in zip(stores, variance):
    print(f"{store}: {var}")

Bengaluru: 3490000
Hyderabad: 1735000
Chennai: 1280000
Mumbai: 1115000
Pune: 810000


Question 54: Percentage Above or Below Target
Calculate the percentage variance from the target using:

Percentage Variance =
(Actual Sales - Target Sales) / Target Sales × 100

In [58]:
percentage_variance = (actual_sales - sales_targets) / sales_targets * 100
print("percentage variance from target:")
print(percentage_variance)


percentage variance from target:
[436.25       385.55555556 400.         371.66666667 405.
 410.86956522]



Question 55: Stores Missing Electronics Target
Identify stores that failed to achieve the Electronics sales target.

In [59]:
sales_targets = np.array([800000, 450000, 320000, 300000, 200000, 230000])
electronics_failed = sales_data[:, 0] < sales_targets[0]
print("Stores missing Electronics target:", stores[electronics_failed])


Stores missing Electronics target: ['Hyderabad' 'Pune']



Question 56: Stores Achieving All Targets
Check whether any store achieved its target in all six product categories.

Use np.all().

In [60]:
sales_targets = np.array([800000, 450000, 320000, 300000, 200000, 230000])
all_targets_achieved = np.all(sales_data >= sales_targets, axis=1)
print("Any store achieved all targets?:", np.any(all_targets_achieved))
print("Stores achieving all targets:", stores[all_targets_achieved])

Any store achieved all targets?: True
Stores achieving all targets: ['Mumbai']


Question 57: Stores Achieving At Least One Target
Identify stores that achieved at least one category target.

Use np.any().

In [61]:
at_least_one_target = np.any(sales_data >= sales_targets, axis=1)
print("Stores achieving at least one target:", stores[at_least_one_target])

Stores achieving at least one target: ['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai']


Part 10: Discount Scenario
SmartMart plans to offer category-wise discounts:

discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])

Question 58: Discount Amount Matrix
Calculate the discount amount for each store-category combination.

Use broadcasting.

In [62]:
discount_rates = np.array([0.10, 0.05, 0.15, 0.12, 0.08, 0.10])
discount_amount = sales_data * discount_rates
print("Discount Amount Matrix:")
print(np.round(discount_amount, 2))

Discount Amount Matrix:
[[ 85000.  21000.  46500.  33000.  15200.  22500.]
 [ 78000.  23000.  44250.  37200.  16800.  24000.]
 [ 92000.  19500.  51000.  31200.  14800.  21500.]
 [105000.  25500.  56250.  41400.  20000.  29000.]
 [ 69000.  20250.  42000.  27000.  14000.  20500.]]



Question 59: Sales After Discount
Calculate the net sales value after applying the category-wise discounts.

In [63]:
sales_after_discount = sales_data * (1 - discount_rates)
print("Sales After Discount Matrix:")
print(np.round(sales_after_discount, 2))

Sales After Discount Matrix:
[[765000. 399000. 263500. 242000. 174800. 202500.]
 [702000. 437000. 250750. 272800. 193200. 216000.]
 [828000. 370500. 289000. 228800. 170200. 193500.]
 [945000. 484500. 318750. 303600. 230000. 261000.]
 [621000. 384750. 238000. 198000. 161000. 184500.]]


Question 60: Profit After Discount
Assuming costs remain unchanged, calculate the new profit after the discounts are applied.

In [64]:
sales_after_discount = sales_data * (1 - discount_rates)
profit_after_discount = sales_after_discount - cost_data
print("Profit After Discount Matrix:")
print(np.round(profit_after_discount, 2))

Profit After Discount Matrix:
[[125000.  84000.  43500.  37000.  49800.  42500.]
 [112000.  87000.  40750.  47800.  53200.  46000.]
 [128000.  75500.  44000.  33800.  50200.  38500.]
 [155000.  94500.  53750.  53600.  65000.  56000.]
 [ 91000.  74750.  33000.  28000.  46000.  39500.]]


Question 61: Profit Margin After Discount
Calculate the new profit margin after applying discounts.

In [65]:
discounted_sales = sales_data * (1 - discount_rates)
discounted_profit = discounted_sales - cost_data
profit_margin_after_discount = np.round((discounted_profit / discounted_sales) * 100, 2)
print("Profit Margin After Discount (%):\n", profit_margin_after_discount)

Profit Margin After Discount (%):
 [[16.34 21.05 16.51 15.29 28.49 20.99]
 [15.95 19.91 16.25 17.52 27.54 21.3 ]
 [15.46 20.38 15.22 14.77 29.49 19.9 ]
 [16.4  19.5  16.86 17.65 28.26 21.46]
 [14.65 19.43 13.87 14.14 28.57 21.41]]


Question 62: Loss-Making Transactions
Check whether any store-category combination becomes loss-making after discounts.

Display the affected store and category names.

In [66]:
# Check for loss-making transactions (discounted_profit < 0)
loss_mask = discounted_profit < 0

if np.any(loss_mask):
    loss_stores, loss_cats = np.where(loss_mask)
    for s_idx, c_idx in zip(loss_stores, loss_cats):
        print(f"Store: {stores[s_idx]}, Category: {categories[c_idx]}")
else:
    print("No store-category combination becomes loss-making after discounts.")

No store-category combination becomes loss-making after discounts.


Question 63: Discount Impact Calculate how much total revenue the company loses because of the proposed discounts.

In [67]:

discount_amount=sales_data*discount_rates
total_revenue_lost = np.sum(discount_amount)
print(f"Total revenue lost due to discounts: {total_revenue_lost:.2f}")

print(discount_amount)

Total revenue lost due to discounts: 1146350.00
[[ 85000.  21000.  46500.  33000.  15200.  22500.]
 [ 78000.  23000.  44250.  37200.  16800.  24000.]
 [ 92000.  19500.  51000.  31200.  14800.  21500.]
 [105000.  25500.  56250.  41400.  20000.  29000.]
 [ 69000.  20250.  42000.  27000.  14000.  20500.]]


Question 64: Store Most Affected by Discounts Identify the store that loses the highest amount of revenue due to discounts.

In [68]:
#Store Most Affected by Discounts Identify the store that loses the highest amount of revenue due to discounts.
discount=np.sum(sales_data*discount_rates,axis=1)
max_discount=np.argmax(discount)
store_name=stores[max_discount]
print(store_name)
print(discount[max_discount])

Mumbai
277150.0


Part 11: Tax and Price Adjustment The government introduces category-wise tax rates:

tax_rates = np.array([ 0.18, 0.05, 0.12, 0.18, 0.18, 0.12 ])

 Question 65: Tax Collection Matrix Calculate the tax collected on sales for each store and category.



In [69]:

tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])

tax=sales_data*tax_rates
print(tax)

[[153000.  21000.  37200.  49500.  34200.  27000.]
 [140400.  23000.  35400.  55800.  37800.  28800.]
 [165600.  19500.  40800.  46800.  33300.  25800.]
 [189000.  25500.  45000.  62100.  45000.  34800.]
 [124200.  20250.  33600.  40500.  31500.  24600.]]


Question 66: Sales Including Tax Calculate the final customer billing value after adding tax.

In [70]:

tax=sales_data*discount_rates
print(cost_data+tax)

[[725000. 336000. 266500. 238000. 140200. 182500.]
 [668000. 373000. 254250. 262200. 156800. 194000.]
 [792000. 314500. 296000. 226200. 134800. 176500.]
 [895000. 415500. 321250. 291400. 185000. 234000.]
 [599000. 330250. 247000. 197000. 129000. 165500.]]


Question 67: Store-Wise Tax Collection Calculate the total tax collected by each store

In [71]:

tax_store=np.sum(sales_data*tax_rates,axis=1)
print(tax_store)

[321900. 321200. 331800. 401400. 274650.]


Question 68: Category-Wise Tax Collection Calculate total tax collected for each category.

In [72]:

tax=np.sum(sales_data*tax_rates,axis=0)
print(tax)


[772200. 109250. 192000. 254700. 181800. 141000.]


Question 69: Highest Tax-Contributing Store Identify the store that contributes the highest tax amount.

In [73]:
tax=np.sum(sales_data*tax_rates,axis=1)
max_tax_store=np.argmax(tax)
print(max_tax_store)
print(stores[max_tax_store])

3
Mumbai


Part 12: Array Modification

Question 70: Updated Pune Electronics Sales The Pune store reports that its Electronics sales were entered incorrectly.

Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.

Make the change in a copied array without modifying the original array.

In [74]:
sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])
new_sales=sales_data.copy()
new_sales[stores=="Pune",categories=="Electronics"]=740000
print(new_sales)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 740000  405000  280000  225000  175000  205000]]


Question 71: Revised Beauty Cost Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.

Create an updated cost array.

In [75]:

new_cost_data=cost_data.copy()
cost_per=cost_data*0.08
new_cost=cost_data-cost_per
new_cost_data[:,categories=="Beauty"]=new_cost[:,categories=="Beauty"]
print(cost_data)
print(new_cost_data)

[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]
[[640000 315000 220000 205000 115000 160000]
 [590000 350000 210000 225000 128800 170000]
 [700000 295000 245000 195000 110400 155000]
 [790000 390000 265000 250000 151800 205000]
 [530000 310000 205000 170000 105800 145000]]


Question 72: Furniture Cost Increase Furniture costs increase by 12% for all stores.

Update only the Furniture column.

In [76]:

new_cost_data=cost_data.copy()
cost_per=cost_data*1.12
new_cost=cost_data+cost_per
new_cost_data[:,categories=="Furniture"]=new_cost[:,categories=="Furniture"]
print(new_cost_data)

[[640000 315000 220000 434600 125000 160000]
 [590000 350000 210000 477000 140000 170000]
 [700000 295000 245000 413400 120000 155000]
 [790000 390000 265000 530000 165000 205000]
 [530000 310000 205000 360400 115000 145000]]


Question 73: Store Closure Simulation Assume the Pune store is temporarily closed.

Remove Pune’s sales and cost data from the analysis using np.delete().

In [77]:

new_sales=sales_data.copy()
new_costs=cost_data.copy()
new_value1=np.delete(new_sales,np.where(stores=="Pune"),axis=0)
new_value2=np.delete(new_costs,np.where(stores=="Pune"),axis=0)
print(new_value1)
print(new_value2)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]]
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]]


Question 74: Adding a New Store A new Delhi store is opened with the following data:

delhi_sales = np.array([ 880000, 475000, 330000, 290000, 215000, 250000 ])

delhi_cost = np.array([ 665000, 360000, 235000, 215000, 145000, 180000 ])

In [78]:

delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])


In [79]:

import numpy as np
delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])
new_sales_data=np.vstack((sales_data,delhi_sales))
new_cost_data=np.vstack((cost_data,delhi_cost))
print(new_sales_data)
print(new_cost_data)
new_store=np.append(stores,"Delhi")
print(new_store)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 880000  475000  330000  290000  215000  250000]]
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]
 [665000 360000 235000 215000 145000 180000]]
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune' 'Delhi']


Question 75: Adding a New Product Category SmartMart starts selling Home Appliances.

home_appliance_sales = np.array([ 360000, 325000, 390000, 420000, 295000 ])

home_appliance_cost = np.array([ 265000, 240000, 285000, 305000, 225000 ]) Add the new category as a column using np.column_stack() or np.hstack().

In [80]:
import numpy as np
home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

In [91]:


home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])
new_sales=np.column_stack((sales_data,home_appliance_sales))
new_cost=np.column_stack((cost_data,home_appliance_cost))
print(new_sales)
print(new_cost)
new_category=np.append(categories,"Homeappliances")
print(new_category)

[[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 690000  405000  280000  225000  175000  205000  295000]]
[[640000 315000 220000 205000 125000 160000 265000]
 [590000 350000 210000 225000 140000 170000 240000]
 [700000 295000 245000 195000 120000 155000 285000]
 [790000 390000 265000 250000 165000 205000 305000]
 [530000 310000 205000 170000 115000 145000 225000]]
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports'
 'Homeappliances']



Part 13: Sorting and Ranking Question 76: Sort Stores by Sales Sort stores in ascending order based on total sales.

Display store names and sales totals.


In [82]:

total_sales_data=np.sum(sales_data,axis=1)
sorting_order=np.argsort(total_sales_data)
for index in sorting_order:
  print(stores[index],":",total_sales_data[index])

Pune : 1980000
Bengaluru : 2270000
Hyderabad : 2295000
Chennai : 2310000
Mumbai : 2820000


Question 77: Rank Stores by Profit Rank stores from highest to lowest total profit.

Use np.argsort().

In [83]:

profit=np.sum(sales_data-cost_data,axis=1)
sorting_profit=np.argsort(-profit)
for index in sorting_profit:
  print(stores[index],":",profit[index])


Mumbai : 755000
Hyderabad : 610000
Bengaluru : 605000
Chennai : 600000
Pune : 505000



Question 78: Sort Categories by Revenue Sort product categories from highest to lowest total revenue.

In [84]:

revenue=np.sum(sales_data,axis=0)
sorting=np.argsort(-revenue)
for index in sorting:
  print(categories[index],":",revenue[index])

Electronics : 4290000
Groceries : 2185000
Clothing : 1600000
Furniture : 1415000
Sports : 1175000
Beauty : 1010000


Question 79: Top Three Store-Category Sales Find the three highest individual sales values in the complete sales matrix.

Display their:

Sales value Store name Category name

In [85]:


new_sales=sales_data.flatten()
sorting=np.argsort(-new_sales)[0:3]
print(sorting)
for index in sorting:
  row,col=np.unravel_index(index,sales_data.shape)
  print(stores[row],":",categories[col],":",sales_data[row,col])

[18 12  0]
Mumbai : Electronics : 1050000
Chennai : Electronics : 920000
Bengaluru : Electronics : 850000


Question 80: Bottom Three Profits Find the three lowest profit values in the profit matrix.

In [86]:

profit=sales_data-cost_data
flattening=profit.flatten()
sorting=np.argsort(flattening)[0:3]
for index in sorting:
  row,col=np.unravel_index(index,profit.shape)
  print(stores[row],categories[col],profit[row,col])

Pune Furniture 55000
Pune Sports 60000
Chennai Sports 60000


Part 14: Statistical Analysis Question 81: Sales Statistics Calculate the following for the complete sales array:

Minimum Maximum Mean Median Standard deviation Variance 25th percentile 50th percentile 75th percentile

In [87]:

print(np.min(sales_data))
print(np.max(sales_data))
print(np.mean(sales_data))
print(np.median(sales_data))
print(np.std(sales_data))
print(np.var(sales_data))
print(np.percentile(sales_data,25))
print(np.percentile(sales_data,50))
print(np.percentile(sales_data,75))

175000
1050000
389166.6666666667
302500.0
230322.53954448793
53048472222.222206
228750.0
302500.0
416250.0


Question 82: Store-Wise Standard Deviation Calculate the sales standard deviation for every store.

Use this value to determine which store has the most variation between product categories.

In [88]:
standard_deviation=np.std(sales_data,axis=1)
max_store=np.argmax(standard_deviation)
store_name=stores[max_store]
print(store_name)
print(standard_deviation[max_store])


Mumbai
271860.871280391


Question 83: Category-Wise Standard Deviation Determine which product category has the highest variation in sales across stores.

In [89]:
standard_deviation=np.std(sales_data,axis=0)
max_store=np.argmax(standard_deviation)
print(categories[max_store],":",standard_deviation[max_store])


Electronics : 122539.78945632312


Question 84: Sales Above Company Average Calculate the company-wide average sales value.

Count how many store-category sales values are above this average.



In [90]:
average_sales=np.mean(sales_data)
max_val=sales_data > average_sales
counting_max_val=np.sum(max_val)
print(counting_max_val)


10


Question 85: Outlier Detection Treat any sales value greater than:

Mean + 1.5 × Standard Deviation as a high-value outlier.

Identify all such sales values.

In [92]:
mean_val=np.mean(sales_data)
std_val=np.std(sales_data)
outlier_val=mean_val+1.5*std_val
counting_outlier=np.where(sales_data > outlier_val)
sales_val=sales_data[counting_outlier]
print(sales_val)

[ 850000  780000  920000 1050000]


Part 15: Reshaping and Transformation

Question 86: Flatten Sales Data Convert the two-dimensional sales array into a one-dimensional array using:

flatten() ravel() Explain the difference between the two methods.

In [93]:
usage_flatten=sales_data.flatten()
usage_ravel=sales_data.ravel()
print(sales_data)
print(usage_flatten)
print(usage_ravel)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]


Question 87: Reshape Sales Data Reshape the 5 × 6 sales array into:

3 × 10 10 × 3 2 × 15 15 × 2 Verify that no data is lost.

In [94]:

print(sales_data)
sales1=sales_data.reshape(3,10)
sales2=sales_data.reshape(10,3)
sales3=sales_data.reshape(2,15)
sales4=sales_data.reshape(15,2)
print(sales1)
print(sales2)
print(sales3)
print(sales4)
print(sales_data.size)
print(sales1.size)
print(sales2.size)
print(sales3.size)
print(sales4.size)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]
[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000]
 [ 210000  240000  920000  390000  340000  260000  185000  215000 1050000
   510000]
 [ 375000  345000  250000  290000  690000  405000  280000  225000  175000
   205000]]
[[ 850000  420000  310000]
 [ 275000  190000  225000]
 [ 780000  460000  295000]
 [ 310000  210000  240000]
 [ 920000  390000  340000]
 [ 260000  185000  215000]
 [1050000  510000  375000]
 [ 345000  250000  290000]
 [ 690000  405000  280000]
 [ 225000  175000  205000]]
[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000  210000  240000  920000  390000  340000]
 [ 260000  185000  215000 1050000  510000  375000  345000  250000  290000
   690000  405000 

Question 88: Transpose Sales Data Transpose the sales array so that:

Rows represent product categories Columns represent stores Display the new shape.

In [95]:

transpose_val=sales_data.transpose()
print(transpose_val)
print(transpose_val.shape)

[[ 850000  780000  920000 1050000  690000]
 [ 420000  460000  390000  510000  405000]
 [ 310000  295000  340000  375000  280000]
 [ 275000  310000  260000  345000  225000]
 [ 190000  210000  185000  250000  175000]
 [ 225000  240000  215000  290000  205000]]
(6, 5)


Question 89: Combined Sales and Cost Array Stack sales_data and cost_data vertically.

Display the resulting shape.

In [96]:
sales_stack=np.vstack((sales_data,cost_data))
print(sales_stack)
print(sales_stack.shape)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 640000  315000  220000  205000  125000  160000]
 [ 590000  350000  210000  225000  140000  170000]
 [ 700000  295000  245000  195000  120000  155000]
 [ 790000  390000  265000  250000  165000  205000]
 [ 530000  310000  205000  170000  115000  145000]]
(10, 6)


Question 90: Store-Level Combined Data Create a three-dimensional array where:

First layer contains sales data Second layer contains cost data Use np.stack().

Display the shape of the new array.

In [97]:

three_d=np.stack((sales_data,cost_data))
print(three_d.shape)

(2, 5, 6)


Part 16: Missing Data Scenario The company discovers that some sales values were not recorded.

In [98]:

sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

Question 91: Missing Value Detection Find:

Total number of missing values Location of missing values Stores and categories containing missing values

In [99]:

total_missing=np.isnan(sales_with_missing)
summation=np.sum(total_missing)
location=np.argwhere(total_missing)
store_name=stores[location]
category_name=categories[location]
print(total_missing)
print(summation)
print(location)
for i,j in location:
  print(stores[i],":",categories[j])
# print(store_name)

# print(store)

[[False False  True False False False]
 [False False False  True False False]
 [False False False False False False]
 [False  True False False False False]
 [False False False False  True False]]
4
[[0 2]
 [1 3]
 [3 1]
 [4 4]]
Bengaluru : Clothing
Hyderabad : Furniture
Mumbai : Groceries
Pune : Beauty


Question 92: Replace Missing Values with Zero Replace all missing sales values with zero.

In [100]:

sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])
replacing_val=np.nan_to_num(sales_with_missing,nan=0)
print(replacing_val)


[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


Question 93: Replace with Company Average Replace missing values with the overall average of available sales values.

Use np.nanmean().

In [101]:
average=round(np.nanmean(sales_with_missing),2)
replace_val=np.nan_to_num(sales_with_missing,nan=average)
print(replace_val)

[[ 850000.    420000.    398846.15  275000.    190000.    225000.  ]
 [ 780000.    460000.    295000.    398846.15  210000.    240000.  ]
 [ 920000.    390000.    340000.    260000.    185000.    215000.  ]
 [1050000.    398846.15  375000.    345000.    250000.    290000.  ]
 [ 690000.    405000.    280000.    225000.    398846.15  205000.  ]]


Question 94: Replace with Category Average Replace each missing value with the average sales value of its respective product category.

In [102]:
average_sales=np.nanmean(sales_with_missing,axis=0)
sales_copy=sales_with_missing.copy()
index=np.argwhere(np.isnan(sales_copy))
print(index)
for i,j in index:
  sales_copy[i,j]=average_sales[j]
print(sales_copy)

[[0 2]
 [1 3]
 [3 1]
 [4 4]]
[[ 850000.  420000.  322500.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  276250.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  418750.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  208750.  205000.]]


Question 95: Missing Value Impact Compare total sales before and after replacing missing values with zero.

In [103]:
sales_sum_without_replacing=np.nansum(sales_with_missing)
replacement_vals=np.nan_to_num(sales_with_missing,nan=0)
sales_sum_with_replacement=np.nansum(replacement_vals)
print(sales_sum_without_replacing)
print(sales_sum_with_replacement)
print("difference:",sales_sum_without_replacing-sales_sum_with_replacement)

10370000.0
10370000.0
difference: 0.0


Part 17: Conditional Business Decisions Question 96: Store Performance Labels Classify each store based on total sales:

"Excellent": Total sales above ₹28,00,000 "Good": Total sales between ₹24,00,000 and ₹28,00,000 "Needs Improvement": Total sales below ₹24,00,000 Use np.select().

In [106]:
sales_sum=np.sum(sales_data,axis=1)

result = np.select((sales_sum > 2800000,(sales_sum>2400000) & (sales_sum <2800000),sales_sum < 2400000),
                   ("Excellent","Good","Needs Improvement"),
                   default = "Unknow"
                   )
print(result)

['Needs Improvement' 'Needs Improvement' 'Needs Improvement' 'Excellent'
 'Needs Improvement']


Question 97: Profitability Classification Classify each store-category combination as:

"Highly Profitable": Profit above ₹2,00,000 "Profitable": Profit between ₹1,00,000 and ₹2,00,000 "Low Profit": Profit below ₹1,00,000 "Loss": Profit below zero

In [105]:
profit=sales_data-cost_data
result = np.select((profit > 200000,(profit>100000) & (profit <200000),profit < 100000,profit<0),
                   ("Highly Profitable","Profitable","Low Profit","Loss"),
                   default = "Unknown"
                   )
print(result)


[['Highly Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Profitable' 'Profitable' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']]


Question 98: Expansion Recommendation A store is eligible for expansion when:

Total sales are above ₹25,00,000 Total profit is above ₹7,00,000 Overall profit margin is above 25% Identify eligible stores.

In [107]:

total_profit=np.sum(sales_data-cost_data,axis=1)
total_sales=np.sum(sales_data,axis=1)
total_cost=np.sum(cost_data,axis=1)

profit_margin=(total_profit/total_sales)*100
result=((total_sales > 2500000) & (total_profit >700000)&(profit_margin >np.percentile(profit_margin,25)))
print(result)
indices=np.where(result)
print("Result:",indices)
stores_names=stores[indices]
print(stores_names)

[False False False  True False]
Result: (array([3]),)
['Mumbai']


Question 99: Category Promotion Recommendation A product category should receive additional promotion when:

Average sales are below ₹3,00,000 Profit margin is above 25% Identify the categories that satisfy these conditions.

In [108]:
average=np.mean(sales_data,axis=0)
total_profit=np.sum(sales_data-cost_data,axis=0)
total_sales=np.sum(sales_data,axis=0)

profit_margin=(total_profit/total_sales)*100
result=((average <300000)&(profit_margin>(np.percentile(profit_margin,25))))
print(result)
indices=np.where(result)
category_name=categories[indices]
print("category:",category_name)

[False False False  True  True  True]
category: ['Furniture' 'Beauty' 'Sports']


Question 100: Cost Optimization Recommendation Find store-category combinations where:

Cost is greater than ₹2,50,000 Profit margin is below 25% These combinations should be reviewed for cost optimization.

In [109]:


total_profit=sales_data-cost_data
profit_margin=(total_profit/sales_data)*100
result=((cost_data >250000)&(profit_margin <25))
indices=np.argwhere(result)
print(profit_margin)
print(result)
print(indices)
for i,j in indices:
  print(stores[i],categories[j])

[[24.70588235 25.         29.03225806 25.45454545 34.21052632 28.88888889]
 [24.35897436 23.91304348 28.81355932 27.41935484 33.33333333 29.16666667]
 [23.91304348 24.35897436 27.94117647 25.         35.13513514 27.90697674]
 [24.76190476 23.52941176 29.33333333 27.53623188 34.         29.31034483]
 [23.1884058  23.45679012 26.78571429 24.44444444 34.28571429 29.26829268]]
[[ True False False False False False]
 [ True  True False False False False]
 [ True  True False False False False]
 [ True  True False False False False]
 [ True  True False False False False]]
[[0 0]
 [1 0]
 [1 1]
 [2 0]
 [2 1]
 [3 0]
 [3 1]
 [4 0]
 [4 1]]
Bengaluru Electronics
Hyderabad Electronics
Hyderabad Groceries
Chennai Electronics
Chennai Groceries
Mumbai Electronics
Mumbai Groceries
Pune Electronics
Pune Groceries


Part 18: Inventory Scenario Use the following inventory arrays:

In [110]:
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])


Question 101: Closing Stock Calculate closing stock using:

Closing Stock = Opening Stock - Units Sold

In [111]:

closing_stock = opening_stock - units_sold
print(closing_stock)

[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


Question 102: Low-Stock Identification Identify store-category combinations where closing stock is below 30 units.

In [112]:
closing_stock = opening_stock - units_sold
result=closing_stock < 30
indices=np.argwhere(result)
print(indices)
for i,j in indices:
  print(stores[i],categories[j])

[[0 0]
 [0 3]
 [1 0]
 [1 3]
 [2 0]
 [2 3]
 [3 0]
 [4 0]
 [4 3]]
Bengaluru Electronics
Bengaluru Furniture
Hyderabad Electronics
Hyderabad Furniture
Chennai Electronics
Chennai Furniture
Mumbai Electronics
Pune Electronics
Pune Furniture


Question 103: Stock Availability Percentage Calculate the percentage of opening stock that remains unsold.

In [113]:

unsold=opening_stock-units_sold
result=(unsold/opening_stock)*100
print(result)

[[20.83333333 15.55555556 20.         27.77777778 24.         22.22222222]
 [22.72727273 16.         17.85714286 25.         22.22222222 22.5       ]
 [19.23076923 16.66666667 15.625      29.41176471 25.         23.52941176]
 [16.66666667 14.54545455 15.71428571 25.         21.66666667 20.45454545]
 [25.         17.5        21.15384615 26.66666667 25.         25.        ]]


Question 104: Fast-Moving Products A product is considered fast-moving when more than 80% of its opening stock has been sold.

Identify fast-moving store-category combinations.

In [114]:
per_opening=(units_sold/opening_stock)*100
s=np.argwhere(per_opening > 80)
print(s)
for i,j in s:
  print(stores[i],categories[j])

[[0 1]
 [1 1]
 [1 2]
 [2 0]
 [2 1]
 [2 2]
 [3 0]
 [3 1]
 [3 2]
 [4 1]]
Bengaluru Groceries
Hyderabad Groceries
Hyderabad Clothing
Chennai Electronics
Chennai Groceries
Chennai Clothing
Mumbai Electronics
Mumbai Groceries
Mumbai Clothing
Pune Groceries


Question 105: Category-Wise Units Sold Calculate the total units sold for each product category.

In [115]:
total_units_sold=np.sum(units_sold,axis=0)
print(total_units_sold)

[ 485 1950 1240  345  980  720]


Question 106: Store-Wise Units Sold Calculate total units sold by each store.

In [116]:

total_units_sold=np.sum(units_sold,axis=1)
print(total_units_sold)

[1110 1175 1095 1390  950]


Question 107: Best Store by Unit Sales Identify the store that sold the highest total number of units.

In [117]:

store_names=np.sum(units_sold,axis=1)
indices=np.argmax(store_names)
print(indices)
print(stores[indices])

3
Mumbai


Question 108: Reorder Requirement A store should reorder a category when closing stock is below 25 units.

Create a Boolean reorder matrix.

In [118]:
closing_stock = opening_stock - units_sold
reordering=closing_stock < 25
print(reordering)


[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


Question 109: Reorder Quantity Assume each category must maintain 100 units after reordering.

Calculate reorder quantities only for combinations where closing stock is below 25.

For all other combinations, return zero.

In [119]:
closing_stock=opening_stock-units_sold
result=np.where(closing_stock < 25,100-closing_stock,0)
print(result)

[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


Part 19: Advanced NumPy Questions Question 110: Cumulative Store Sales Calculate cumulative category sales for each store using np.cumsum().

In [120]:

cumulative_sales=np.cumsum(sales_data,axis=1)
print(cumulative_sales)


[[ 850000 1270000 1580000 1855000 2045000 2270000]
 [ 780000 1240000 1535000 1845000 2055000 2295000]
 [ 920000 1310000 1650000 1910000 2095000 2310000]
 [1050000 1560000 1935000 2280000 2530000 2820000]
 [ 690000 1095000 1375000 1600000 1775000 1980000]]


Question 111: Cumulative Company Sales Flatten the sales array and calculate cumulative company sales.

In [121]:

flattening=sales_data.flatten()
cumulative_sales=np.cumsum(flattening)
print(cumulative_sales)

[  850000  1270000  1580000  1855000  2045000  2270000  3050000  3510000
  3805000  4115000  4325000  4565000  5485000  5875000  6215000  6475000
  6660000  6875000  7925000  8435000  8810000  9155000  9405000  9695000
 10385000 10790000 11070000 11295000 11470000 11675000]


Question 112: Sales Difference Between Categories Calculate the difference between consecutive category sales for each store using np.diff().

In [122]:
result=np.diff(sales_data,axis=1)
print(result)

[[-430000 -110000  -35000  -85000   35000]
 [-320000 -165000   15000 -100000   30000]
 [-530000  -50000  -80000  -75000   30000]
 [-540000 -135000  -30000  -95000   40000]
 [-285000 -125000  -55000  -50000   30000]]


Question 113: Unique Sales Values Find all unique sales values in sales_data.

Also count the frequency of each value.

In [123]:
unique_vals=np.unique(sales_data)
print(unique_vals)
counting=np.unique(unique_vals,return_counts=True)
print(counting)

[ 175000  185000  190000  205000  210000  215000  225000  240000  250000
  260000  275000  280000  290000  295000  310000  340000  345000  375000
  390000  405000  420000  460000  510000  690000  780000  850000  920000
 1050000]
(array([ 175000,  185000,  190000,  205000,  210000,  215000,  225000,
        240000,  250000,  260000,  275000,  280000,  290000,  295000,
        310000,  340000,  345000,  375000,  390000,  405000,  420000,
        460000,  510000,  690000,  780000,  850000,  920000, 1050000]), array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1]))


Question 114: Search for Specific Sales Check whether the value ₹4,20,000 exists in the sales array.

Return its location.

In [124]:
result=np.argwhere(sales_data==420000)
print(result)

[[0 1]]


Question 115: Compare Sales and Cost Create a Boolean array showing whether sales are greater than cost for every combination.

Verify whether all combinations are profitable using np.all().

In [125]:
result=(sales_data > cost_data)
indices=np.argwhere(result)
print(indices)
profitabble=np.all(result)
print(profitabble)

[[0 0]
 [0 1]
 [0 2]
 [0 3]
 [0 4]
 [0 5]
 [1 0]
 [1 1]
 [1 2]
 [1 3]
 [1 4]
 [1 5]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [2 4]
 [2 5]
 [3 0]
 [3 1]
 [3 2]
 [3 3]
 [3 4]
 [3 5]
 [4 0]
 [4 1]
 [4 2]
 [4 3]
 [4 4]
 [4 5]]
True


Question 116: Clip Profit Values For reporting purposes, management wants profit values limited to:

Minimum: ₹75,000 Maximum: ₹2,50,000 Use np.clip() to create a reporting profit array.

In [126]:

profit=sales_data-cost_data
result=np.clip(profit,75000,250000)
print(result)

[[210000 105000  90000  75000  75000  75000]
 [190000 110000  85000  85000  75000  75000]
 [220000  95000  95000  75000  75000  75000]
 [250000 120000 110000  95000  85000  85000]
 [160000  95000  75000  75000  75000  75000]]


Question 117: Normalize Sales Data Normalize all sales values using min-max normalization:

Normalized Sales = (Sales - Minimum Sales) / (Maximum Sales - Minimum Sales)

In [127]:

normalized_sales=(sales_data - np.min(sales_data))/(np.max(sales_data - np.min(sales_data)))
print(normalized_sales)

[[0.77142857 0.28       0.15428571 0.11428571 0.01714286 0.05714286]
 [0.69142857 0.32571429 0.13714286 0.15428571 0.04       0.07428571]
 [0.85142857 0.24571429 0.18857143 0.09714286 0.01142857 0.04571429]
 [1.         0.38285714 0.22857143 0.19428571 0.08571429 0.13142857]
 [0.58857143 0.26285714 0.12       0.05714286 0.         0.03428571]]


Question 118: Standardize Sales Data Standardize sales using:

Standardized Sales = (Sales - Mean Sales) / Standard Deviation

In [128]:

standard_sales=((sales_data - np.mean(sales_data))/(np.std(sales_data)))
print(standard_sales)

[[ 2.00081735  0.13387024 -0.34372088 -0.49568169 -0.86472938 -0.71276857]
 [ 1.69689573  0.30753974 -0.40884695 -0.34372088 -0.77789463 -0.64764251]
 [ 2.30473897  0.00361811 -0.21346876 -0.56080776 -0.88643807 -0.75618594]
 [ 2.86916484  0.52462661 -0.06150795 -0.19176007 -0.60422513 -0.43055563]
 [ 1.30613936  0.06874418 -0.47397301 -0.71276857 -0.92985544 -0.79960332]]


Question 119: Round Values Convert profit margin values into:

Two decimal places Nearest whole number Floor values Ceiling values

In [129]:
total_profit=sales_data-cost_data
profit_margin=(total_profit/sales_data)*100
print(np.round(profit_margin,2))
print(np.round(profit_margin))
print(np.floor(profit_margin))
print(np.ceil(profit_margin))

[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]
[[25. 25. 29. 25. 34. 29.]
 [24. 24. 29. 27. 33. 29.]
 [24. 24. 28. 25. 35. 28.]
 [25. 24. 29. 28. 34. 29.]
 [23. 23. 27. 24. 34. 29.]]
[[24. 25. 29. 25. 34. 28.]
 [24. 23. 28. 27. 33. 29.]
 [23. 24. 27. 25. 35. 27.]
 [24. 23. 29. 27. 34. 29.]
 [23. 23. 26. 24. 34. 29.]]
[[25. 25. 30. 26. 35. 29.]
 [25. 24. 29. 28. 34. 30.]
 [24. 25. 28. 25. 36. 28.]
 [25. 24. 30. 28. 34. 30.]
 [24. 24. 27. 25. 35. 30.]]



Question 120: Save and Load Data Save the following arrays as NumPy binary files:

sales_data.npy cost_data.npy profit_data.npy Load them back and verify that the loaded arrays are equal to the original arrays.

In [130]:
profit_data=sales_data-cost_data
np.save("sales_data.npy",sales_data)
np.save("cost_data.npy",cost_data)
np.save("profit_data.npy",profit_data)
np.load("sales_data.npy")
np.load("cost_data.npy")
np.load("profit_data.npy")

array([[210000, 105000,  90000,  70000,  65000,  65000],
       [190000, 110000,  85000,  85000,  70000,  70000],
       [220000,  95000,  95000,  65000,  65000,  60000],
       [260000, 120000, 110000,  95000,  85000,  85000],
       [160000,  95000,  75000,  55000,  60000,  60000]])

In [131]:
np.load("cost_data.npy")

array([[640000, 315000, 220000, 205000, 125000, 160000],
       [590000, 350000, 210000, 225000, 140000, 170000],
       [700000, 295000, 245000, 195000, 120000, 155000],
       [790000, 390000, 265000, 250000, 165000, 205000],
       [530000, 310000, 205000, 170000, 115000, 145000]])

In [132]:

import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])
discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])
tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


In [133]:

profit=sales_data-cost_data
profit_margin=(profit/sales_data)*100
profit_margin1=((np.sum(profit,axis=1))/(np.sum(sales_data,axis=1)))*100
target_achieved1=np.sum(sales_data>sales_targets,axis=1)
target_achieved2=np.sum(sales_data>sales_targets,axis=0)
expansion=(np.sum(sales_data,axis=1) > 2500000) & (np.sum(profit) > 700000) & (profit_margin1 > 25)
print(stores[expansion])
best=np.sum(sales_data,axis=1)
best_cost=np.sum(cost_data,axis=1)
best_cost_sales=np.max(best_cost)
worst_cost_sales=np.min(best_cost)
best_store=np.argmax(best)
worst_store=np.argmin(best)
#best profit
profit_sum=np.sum(profit,axis=1)
profit_store=np.max(profit_sum)
print(profit_store)
#best proofit margin
profit_margin_sum=np.round((np.sum(profit,axis=1))/(np.sum(sales_data,axis=1)),2)*100
best_profit_margin=np.max(profit_margin_sum)
print(stores[best_store])
print(stores[worst_store])
print(best_cost_sales)
#best category
best_category=np.sum(sales_data,axis=0)
best_category_name=np.argmax(best_category)
worst_category_name=np.argmin(best_category)
category_sum=np.sum(cost_data,axis=0)
best_category_cost=np.max(category_sum)
print(best_category)
# cateory_name=categories[best_category]
#best sales in category
sales=np.sum(sales_data,axis=0)
sales_max=np.max(sales)
#best profit category
profit_sum1=np.sum(profit,axis=0)
profit_category=np.max(profit_sum1)
#best profit margin
profit_margin_sum1=np.round((np.sum(profit,axis=0))/(np.sum(sales_data,axis=0)),2)*100
best_profit_margin_category=np.max(profit_margin_sum1)
expansion_eligibilities=()
#cost opyimization
cost_sum=np.argmax(np.sum(cost_data,axis=1))
print(cost_sum)
profit_margin0=np.max(np.sum(profit,axis=1)/(np.sum(sales_data,axis=1)))*100
#reordering
closing_stock=opening_stock-units_sold
result1=np.where(closing_stock < 25,100-closing_stock,0)
print(result1)

['Mumbai']
755000
Mumbai
Pune
2065000
[4290000 2185000 1600000 1415000 1010000 1175000]
3
[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


In [134]:

closing_stock=opening_stock-units_sold
result1=np.where(closing_stock < 25,100-closing_stock,0)
print(result1)
indices=np.argwhere(closing_stock < 25)
print(indices)
for i,j in indices:
  print(stores[i],categories[j])

[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]
[[4 3]]
Pune Furniture


In [135]:

print("SMART RETAIL PERFORMANCE REPORT")
print("=====================================")
print("COMPANY SUMMARY")
print("------------------------------------------")
print("Total Sales:",np.sum(sales_data))
print("Total Cost:",np.sum(cost_data))
print("Total_Profit:",np.sum(profit))
print("Profit Margin:",np.sum(profit_margin))
print("Average:",np.mean(sales_data))
print("Highest Sales:",np.max(sales_data))
print("Lowest Sales:",np.min(sales_data))
print("\nSTORE SUMMARY")
print("-------------------------------------")
print("Total Sales:",np.sum(sales_data,axis=1))
print("Total Cost:",np.sum(cost_data,axis=1))
print("Total Profit:",np.sum(profit,axis=1))
print("Profit Margin:",np.round(np.sum(profit_margin,axis=1),2))
print("No Of Targets Achieved:",target_achieved1)
print("Units Sold:",np.sum(units_sold,axis=1))
print("Expansion eligibility:",stores[expansion])
print("\nCATEGORY SUMMARY")
print("-------------------------------------")
print("Total Sales:",np.sum(sales_data,axis=0))
print("Total Cost:",np.sum(cost_data,axis=0))
print("Total Profit:",np.sum(profit,axis=0))
print("Profit Margin:",np.round(np.sum(profit_margin,axis=0),2))
print("No Of Targets Achieved:",target_achieved2)
print("Units Sold:",np.sum(units_sold,axis=0))
print("Average:",np.mean(sales_data,axis=0))
print("\nMANAGEMENT RECOMMENDATIONS")
print("=====================================")
print("\nBEST PERFORMING STORE")
print("------------------------------------------")
print("Best Store:",stores[best_store])
print("Best Sales:",np.max(best))
print("Best Cost:",best_cost_sales)
print("Best_Profit:",profit_store)
print("Best Profit Margin:",best_profit_margin)
print("\nLOWEST PERFORMING STORE")
print("---------------------------------------")
print("Worst Store:",stores[worst_store])
print("Worst Sales:",np.min(best))
print("Worst  Cost:",worst_cost_sales)
print("Worst Profit:",np.min(profit_sum1))
print("Worst Profit Margin:",np.min(profit_margin_sum1))


print("\nMOST PROFITABLE  CATEGORY")
print("---------------------------------------")
print("Best Category:",categories[best_category_name])
print("Best Sales:",np.max(best_category))
print("Best Cost:",np.max(category_sum))
print("Best Profit:",profit_category)
print("Best Profit Margin Category:",best_profit_margin_category)
print("\nWorst Profitable Category")
print("-----------------------------------------")
print("Worst Category:",categories[worst_category_name])
print("Worst Sales:",np.min(best_category))
print("Worst Cost:",np.min(category_sum))
print("Worst Profit:",np.min(profit_sum1))
print("Worst Profit Margin Category:",np.min(profit_margin_sum1))
print("\nEXPANSION RECOMMENDATIONS")
print("-----------------------------------------------")
print("Expansion Eligibilities:",stores[expansion])
print("\nCOST OPTIMIZATION")
print("-------------------------------------")
print("Store:",stores[cost_sum])
print("Category:",categories[cost_sum])
print("Cost:",np.max(np.sum(cost_data,axis=1)))
print("Profit Margin:",profit_margin0)
print("\nINVENTORY REORDER")
print("------------------------------------------")
print("Store:",stores[i])
print("Category:",categories[j])
print("Closing Stock:",closing_stock[i,j])
print("Reorder Quantity:",100-closing_stock[i,j])

SMART RETAIL PERFORMANCE REPORT
COMPANY SUMMARY
------------------------------------------
Total Sales: 11675000
Total Cost: 8600000
Total_Profit: 3075000
Profit Margin: 828.4529274527509
Average: 389166.6666666667
Highest Sales: 1050000
Lowest Sales: 175000

STORE SUMMARY
-------------------------------------
Total Sales: [2270000 2295000 2310000 2820000 1980000]
Total Cost: [1665000 1685000 1710000 2065000 1475000]
Total Profit: [605000 610000 600000 755000 505000]
Profit Margin: [167.29 167.   164.26 168.47 161.43]
No Of Targets Achieved: [1 4 2 6 0]
Units Sold: [1110 1175 1095 1390  950]
Expansion eligibility: ['Mumbai']

CATEGORY SUMMARY
-------------------------------------
Total Sales: [4290000 2185000 1600000 1415000 1010000 1175000]
Total Cost: [3250000 1660000 1145000 1045000  665000  835000]
Total Profit: [1040000  525000  455000  370000  345000  340000]
Profit Margin: [120.93 120.26 141.91 129.85 170.96 144.54]
No Of Targets Achieved: [3 2 2 2 2 2]
Units Sold: [ 485 1950 12